"""Add_syllabus_topics_and_optional_score

Revision ID: 8d33e0b9bd1a
Revises: 24f422717af8
Create Date: 2026-04-19 15:58:32.173790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d33e0b9bd1a'
down_revision: Union[str, Sequence[str], None] = '24f422717af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syllabus_topics', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mark', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('syllabus_topics')

    # ### end Alembic commands ###
